name: C++/CUDA

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-changed-files:
    uses: ./.github/workflows/check-changed-files.yml

  check-format:
    name: Check Code Format
    runs-on: ubuntu-22.04
    needs: check-changed-files
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Check clang-format
      if: needs.check-changed-files.outputs.cpp == 'true'
      run: ./scripts/format_all.sh . --check --exclude "build|wrappers"

  test-linux-curve:
    name: Test on Linux
    runs-on: [self-hosted, Linux, X64, icicle]
    needs: [check-changed-files, check-format]
    strategy:
      matrix:
        curve:
          - name: bn254
            build_args: -DG2=ON

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
    - name: Build curve
      working-directory: ./icicle
      if: needs.check-changed-files.outputs.cpp == 'true'
      run: |
        mkdir -p build && rm -rf build/*
        cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTS=ON -DCURVE=${{ matrix.curve.name }} ${{ matrix.curve.build_args }} -DCUDA_BACKEND=local -S . -B build
        cmake --build build -j
    - name: Run C++ curve Tests
      working-directory: ./icicle/build/tests
      if: needs.check-changed-files.outputs.cpp == 'true'
      run: ctest -R msm --output-on-failure